### ISSUE TITLE
Document only works for hash - incompatible with Rails 5

### ISSUE THREAD

**Issue by cilim** [jsonapi-rb/jsonapi-parser#5]
I'm trying to use the [jsonapi-rails](https://github.com/jsonapi-rb/jsonapi-rails) gem to deserialize the incoming params on an HTTP request, but it's not working as expected.

I tried 2 approaches:

Firstly I followed the instructions from [the guides](http://jsonapi-rb.org/guides/deserialization/deserializing.html) and tried using the default `JSONAPI::Deserializable::Resource.call(json_hash)` like this:

```ruby
class AuthorsController < ApplicationController
  def create
    respond_with Author.create(author_params), class: AuthorSerializer
  end

  private

  def author_params
    JSONAPI::Deserializable::Resource.call(params)  
  end
```

but since the [JSONAPI::Parser::Resource](https://github.com/jsonapi-rb/jsonapi-parser/blob/master/lib/jsonapi/parser/resource.rb) is expecting a hash an error is raised.

The second approach is using the `deserializable_resource` on the controller level:

```ruby
class AuthorsController < ApplicationController
  deserializable_resource :author, only: :create
  
  def create
    respond_with Author.create(author_params), class: AuthorSerializer
  end

  private

  def author_params
    params.require(:author).permit(:name)
  end
```

When I try it like this I get `ActionController::ParameterMissing: param is missing or the value is empty: author` when inspecting the `author_params`. If I inspect the `params` they are looking like this:

```
ActionController::Parameters {"data"=>{"type"=>"authors", "attributes"=>{"name"=>"Author name"}}, "controller"=>"api/v1/authors", "action"=>"create"} permitted: false>
```

which means that the desiralization on the params didn't occur.

Any guidance would be helpful. I'm using ruby 2.3.1p112 and Rails 5.0.1

**Comment by beauby** [comment]
Hi @cilim. The second approach is the supported one for rails. I will look into your issue ASAP, but in the meantime, you can use a workaround based on your first approach: just use `params.to_unsafe_h` in order to get a hash from the parameters.

**Comment by cilim** [comment]
Hi @beauby. Thanks for the help! I'll also transfer this issue to [jsonapi-rails](https://github.com/jsonapi-rb/jsonapi-rails/).
